### ISSUE TITLE
API Inconsistency

### ISSUE THREAD

**Issue by allxrise** [raylib-rs/raylib-rs#71]
`get_render_width` exist but `get_render_height` doesn't.

**Comment by IoIxD** [comment]
This is fixed in the 5.1 branch.
Leaving this open since that branch isn't released yet.

**Comment by haudan** [comment]
This was closed without further details, but `get_render_height` is still missing. Is there any info on this?
